export const TRANSACTION_PAGE_MENU_KEY = "TRANSACTION_PAGE_MENU_KEY_1";

export const MERCHANT_PAGE_MENU_KEY = "MERCHANT_PAGE_MENU_KEY_2";

export const STAFFMANAGMENT_PAGE_MENU_KEY = "STAFFMANAGMENT_PAGE_MENU_KEY_3";

export const CONDUCTOR_PAGE_MENU_KEY = "CONDUCTOR_PAGE_MENU_KEY_4";

export const CARDHOLDER_PAGE_MENU_KEY = "CARDHOLDER_PAGE_MENU_KEY_5";

export const MERCHANT_DRAWER_KEY = "MERCHANT_DRAWER_KEY";

export const CONDUCTER_DRAWER_KEY = "CONDUCTOR_DRAWER_KEY";

export const REGISTER_STAFF_DRAWER_KEY = "REGISTER_STAFF_DRAWER_KEY";

export const API_BASE = "http://localhost:9090";

export const DATE_FORMAT = 'DD/MM/YYYY';

export const DEFAULT_PAGE = 0;

export const DEFAULT_PAGE_SIZE = 10;